# Generated by Django 3.2.9 on 2021-11-29 21:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id_carrro', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_carro', models.CharField(max_length=255)),
                ('fabrica_carro', models.CharField(max_length=255)),
                ('modelo_carro', models.CharField(max_length=255)),
                ('ano_modelo', models.IntegerField()),
                ('motor_carro', models.FloatField()),
                ('kilometragem', models.FloatField()),
                ('status_carro', models.CharField(max_length=40)),
                ('valor_venda', models.FloatField()),
                ('create', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
